variable "cluster_name" {}
variable "eks_role_arn" {}
variable "eks-node-group-role_arn" {}
variable "default_az1_id" {}
variable "default_az2_id" {}
variable "eks-AmazonEKSClusterPolicy_arn" {}
variable "eks-AmazonEKSVPCResourceController_arn" {}
variable "AmazonEKSWorkerNodePolicy_arn" {}
variable "AmazonEKS_CNI_Policy_arn" {}
variable "AmazonEC2ContainerRegistryReadOnly_arn" {}