apiVersion: v1
kind: Service
metadata:
  name: e-commerce-web-app-service
spec:
  selector:
    app: e-commerce-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
