apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-json-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-json
  template:
    metadata:
      labels:
        app: library-json
    spec:
      containers:
        - name: library-json-container
          image: reemwaleed/new-deploymentnew-image:v3.0
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
