apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-json-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-json
  template:
    metadata:
      labels:
        app: library-json
    spec:
      containers:
        - name: library-json-container
          image: reemwaleed/python:bm-project-v10
          volumeMounts:
            - name: library-json-storage
              mountPath: "/mnt/data"

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: library-json-storage
          persistentVolumeClaim:
            claimName: library-json-pvc