apiVersion: v1  # Specifies the API version for the PersistentVolumeClaim
kind: PersistentVolumeClaim  # Defines the kind of resource, in this case, a PersistentVolumeClaim
metadata:
  name: library-json-pvc  # Name of the PersistentVolumeClaim
spec:
  accessModes:
    - ReadWriteOnce  # Access mode indicating that the volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi  # Amount of storage requested for the volume
  storageClassName: manual  # Storage class to be used for provisioning the volume, "manual" refers to a pre-existing volume
