apiVersion: v1  # Specifies the API version for the Pod
kind: Pod  # Defines the kind of resource, in this case, a Pod
metadata:
  name: pod-1  # Name of the Pod
spec:
  containers:
    - name: library-json-container  # Name of the container within the Pod
      image: reemwaleed/new-pod-image:v4.0  # Docker image to use for the container, including a custom tag
      ports:
        - containerPort: 5000  # Port on which the container listens
      command: [ "python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000" ]  # Command to run when the container starts; starts Flask application
      env:
        - name: FLASK_APP  # Environment variable for Flask application
          value: "app.py"  # Specifies the Flask application file
        - name: FLASK_ENV  # Environment variable for Flask environment
          value: "development"  # Specifies the Flask environment as development
      volumeMounts:
        - mountPath: /app/data  # Path in the container where the volume will be mounted
          name: library-json-storage  # Name of the volume to mount
      resources:
        requests:
          memory: "256Mi"  # Minimum amount of memory requested by the container
          cpu: "250m"  # Minimum amount of CPU requested by the container
        limits:
          memory: "512Mi"  # Maximum amount of memory allowed for the container
          cpu: "500m"  # Maximum amount of CPU allowed for the container
  volumes:
    - name: library-json-storage  # Name of the volume to be used in the Pod
      persistentVolumeClaim:
        claimName: library-json-pvc  # Name of the PersistentVolumeClaim to bind to the volume
