apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: library-json-container
      image: reemwaleed/new-pod-imagenew:v3.0 # Updated with custom tag
      ports:
        - containerPort: 5000
      command: [ "python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000" ]
      env:
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_ENV
          value: "development"
      volumeMounts:
        - mountPath: /app/data
          name: library-json-storage
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
  volumes:
    - name: library-json-storage
      persistentVolumeClaim:
        claimName: library-json-pvc
